class ChangeDefaultAnswers < ActiveRecord::Migration[5.1]
  def change
    change_column_default :answers, :answer1,0
    change_column_default :answers, :answer2,0
    change_column_default :answers, :answer3,0
    change_column_default :answers, :answer4,0
    change_column_default :answers, :answer5,0
    change_column_default :answers, :answer6,0
    change_column_default :answers, :answer7,0
    change_column_default :answers, :answer8,0
    change_column_default :answers, :answer9,0
    change_column_default :answers, :answer10,0
    change_column_default :answers, :answer11,0
    change_column_default :answers, :answer12,0
    change_column_default :answers, :answer13,0
    change_column_default :answers, :answer14,0
    change_column_default :answers, :answer15,0
    change_column_default :answers, :answer16,0
    change_column_default :answers, :answer17,0
    change_column_default :answers, :answer18,0
    change_column_default :answers, :answer19,0
    change_column_default :answers, :answer20,0
    change_column_default :answers, :answer21,0
    change_column_default :answers, :answer22,0
    change_column_default :answers, :answer23,0
    change_column_default :answers, :answer24,0
    change_column_default :answers, :answer25,0
    change_column_default :answers, :answer26,0
    change_column_default :answers, :answer27,0
    change_column_default :answers, :answer28,0
    change_column_default :answers, :answer29,0
    change_column_default :answers, :answer30,0
    change_column_default :answers, :answer31,0
    change_column_default :answers, :answer32,0
    change_column_default :answers, :answer33,0
    change_column_default :answers, :answer34,0
    change_column_default :answers, :answer35,0
    change_column_default :answers, :answer36,0
    change_column_default :answers, :answer37,0
    change_column_default :answers, :answer38,0
    change_column_default :answers, :answer39,0
    change_column_default :answers, :answer40,0
    change_column_default :answers, :answer41,0
    change_column_default :answers, :answer42,0
    change_column_default :answers, :answer43,0
    change_column_default :answers, :answer44,0
    change_column_default :answers, :answer45,0
    change_column_default :answers, :answer46,0
    change_column_default :answers, :answer47,0
    change_column_default :answers, :answer48,0
    change_column_default :answers, :answer49,0
    change_column_default :answers, :answer50,0
  end
end
